const String SUPABASE_URL = 'SUPABASE_URL';
const SUPABASE_ANNON_KEY = 'SUPABASE_ANNON_KEY';

const CLIENT_ID = 'CLIENT_ID';
const CLIENT_SECRET = 'CLIENT_SECRET';

const NETWORK_IMAGE_URL = 'NETWORK_IMAGE_URL';
